---
title: "titanic data test again using ml"
output: html_notebook
---

尝试进行titanic测试
```{r}
# rm(list=ls())
titanic.train <- read.csv("train.csv")
titanic.test <- read.csv("test.csv")
titanic.train$IsTrainSet <- TRUE
titanic.test$IsTrainSet <- FALSE
titanic.test$Survived <- NA
titanic.full <- rbind(titanic.train,titanic.test)

dim(titanic.full)
table(titanic.full$IsTrainSet)
titanic.full[titanic.full$Embarked=="","Embarked"] <- "S"
age.median <- median(titanic.full$Age,na.rm=TRUE)
titanic.full[is.na(titanic.full$Age),"Age"] <- age.median
# fare.median <- median(titanic.full$Fare,na.rm=TRUE)
# titanic.full[is.na(titanic.full$Fare),"Fare"] <- fare.median
# 用fare和其他变量的关系线性回归产生插入值
titanic.full[is.na(titanic.full$Fare),"Fare"]
upper.whisker <- boxplot.stats(titanic.full$Fare)$stats[5]
outlier.filter <- titanic.full$Fare < upper.whisker
titanic.full[outlier.filter,]
fare.equation = "Fare~Pclass+Sex+Age+SibSp+Parch+Embarked"
fare.model <- lm(
    formula=fare.equation,
    data=titanic.full[outlier.filter,]
)

fare.row <- titanic.full[
    is.na(titanic.full$Fare),
    c("Pclass","Sex","Age","SibSp","Parch","Embarked")
             ]
fare.predictions <-  predict(fare.model, newdata=fare.row)
titanic.full[is.na(titanic.full$Fare),"Fare"] <- fare.predictions



```

建立模型

```{r}
titanic.full$Pclass <- as.factor(titanic.full$Pclass)
titanic.full$Sex <- as.factor(titanic.full$Sex)
titanic.full$Embarked <- as.factor(titanic.full$Embarked)



# split dataset into train and test
titanic.train <- titanic.full[titanic.full$IsTrainSet==TRUE,]
titanic.test <- titanic.full[titanic.full$IsTrainSet==FALSE,]
titanic.train$Survived <- as.factor(titanic.train$Survived)

library(randomForest)
survived.equation <- "Survived~Pclass+Sex+Age+SibSp+Parch+Fare+Embarked"
survived.formula <- as.formula(survived.equation)

titanic.model <- randomForest(formula = survived.formula, data=titanic.train, ntree = 500, mtry = 3,nodesize = 0.01*nrow(titanic.train))

features.equation <- "Pclass+Sex+Age+SibSp+Parch+Fare+Embarked"

Survived <- predict(titanic.model, newdata=titanic.test)
Survived

PassengerId <- titanic.test$PassengerId
output.df <- as.data.frame(PassengerId)
output.df$Survived <- Survived
write.csv(output.df, file = "Kaggle_submmission.csv", row.names = FALSE)
```

